# Copyright © 2025 Eser KUBALI <lxldev.contact@gmail.com>
# SPDX-License-Identifier: GPL-3.0-or-later
#
# This file is part of vglog-filter and is licensed under
# the GNU General Public License v3.0 or later.
# See the LICENSE file in the project root for details.

name: Clang-Tidy Static Analysis

permissions:
  contents: read

on:
  push:
    paths:
      - 'src/**'
      - 'include/**'
      - 'CMakeLists.txt'
      - '.clang-tidy'
      - '.github/workflows/clang-tidy.yml'
  pull_request:
    paths:
      - 'src/**'
      - 'include/**'
      - 'CMakeLists.txt'
      - '.clang-tidy'
      - '.github/workflows/clang-tidy.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  clang-tidy:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            build-essential cmake ninja-build clang clang-tidy clang-tools
          clang --version
          clang++ --version
          clang-tidy --version

      - name: Configure (CMake + compile_commands.json)
        run: |
          cmake -S . -B build-clang-tidy -G Ninja \
            -DCMAKE_EXPORT_COMPILE_COMMANDS=ON \
            -DCMAKE_BUILD_TYPE=RelWithDebInfo \
            -DCMAKE_C_COMPILER=clang \
            -DCMAKE_CXX_COMPILER=clang++ \
            -DCMAKE_CXX_STANDARD=20 \
            -DCMAKE_CXX_STANDARD_REQUIRED=ON \
            -DPERFORMANCE_BUILD=OFF \
            -DWARNING_MODE=ON \
            -DDEBUG_MODE=OFF \
            -DBUILD_TESTS=ON \
            -DCMAKE_CXX_CLANG_TIDY="clang-tidy;-warnings-as-errors=*"

      - name: Build (runs clang-tidy via CMake)
        run: |
          set -o pipefail
          cmake --build build-clang-tidy -j"$(nproc)" | tee build-clang-tidy/clang-tidy-output.txt

      - name: Upload artifacts (clang-tidy logs & compile commands)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: clang-tidy-artifacts
          path: |
            build-clang-tidy/clang-tidy-output.txt
            build-clang-tidy/compile_commands.json
          if-no-files-found: ignore
