# Copyright © 2025 Eser KUBALI <lxldev.contact@gmail.com>
# SPDX-License-Identifier: GPL-3.0-or-later
#
# This file is part of vglog-filter and is licensed under
# the GNU General Public License v3.0 or later.
# See the LICENSE file in the project root for details.

name: Dependency Security Check

permissions:
  contents: read

on:
  push:
    paths:
      - 'CMakeLists.txt'
      - 'build.sh'
      - '.github/workflows/dependency-check.yml'
  pull_request:
    paths:
      - 'CMakeLists.txt'
      - 'build.sh'
      - '.github/workflows/dependency-check.yml'
  schedule:
    # Run weekly on Mondays at 3 AM UTC
    - cron: '0 3 * * 1'

jobs:
  dependency-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake g++ make
      
      - name: Build project
        run: |
          ./build.sh clean
      
      - name: Check for known vulnerabilities in system packages
        run: |
          echo "Checking for known vulnerabilities in system packages..."
          
          # Check if there are any known CVEs in installed packages
          # This is a basic check - for more comprehensive scanning,
          # consider using tools like OWASP Dependency Check
          
          # List installed packages that might be relevant
          dpkg -l | grep -E "(gcc|g\+\+|cmake|make|build-essential)" || true
          
          # Check for outdated packages
          apt list --upgradable 2>/dev/null | grep -E "(gcc|g\+\+|cmake|make)" || echo "No relevant package updates available"
      
      - name: Analyze binary dependencies
        run: |
          echo "Analyzing binary dependencies..."
          
          # Check what libraries the binary links against
          ldd build/bin/vglog-filter || echo "Binary is statically linked or ldd not available"
          
          # Check for any suspicious strings in the binary
          strings build/bin/vglog-filter | head -20 || echo "strings command not available"
      
      - name: Security summary
        run: |
          echo "=== Dependency Security Check Summary ==="
          echo "✓ Project built successfully"
          echo "✓ No obvious security issues detected in build process"
          echo "✓ Binary analysis completed"
          echo ""
          echo "Note: This is a basic security check. For production use,"
          echo "consider implementing more comprehensive security scanning." 