# Copyright © 2025 Eser KUBALI <lxldev.contact@gmail.com>
# SPDX-License-Identifier: GPL-3.0-or-later
#
# This file is part of vglog-filter and is licensed under
# the GNU General Public License v3.0 or later.
# See the LICENSE file in the project root for details.

name: Memory Sanitizer Testing

permissions:
  contents: read

on:
  push:
    paths:
      - 'src/**'
      - 'CMakeLists.txt'
      - '.github/workflows/memory-sanitizer.yml'
  pull_request:
    paths:
      - 'src/**'
      - 'CMakeLists.txt'
      - '.github/workflows/memory-sanitizer.yml'

jobs:
  memory-sanitizer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup C++ Environment
        uses: ./.github/actions/setup-cpp

      - name: Install Clang and LLVM tools
        run: |
          sudo apt-get update
          sudo apt-get install -y clang llvm
      
      - name: Verify MSAN suppressions file
        run: |
          if [ ! -f "test-workflows/msan_suppressions.txt" ]; then
            echo "Error: MSAN suppressions file not found"
            exit 1
          fi
          echo "MSAN suppressions file found and ready to use"
          wc -l test-workflows/msan_suppressions.txt
      
      - name: Build with Memory Sanitizer
        run: |
          mkdir -p build-msan
          cd build-msan
          cmake -DCMAKE_CXX_COMPILER=clang++ \
                -DCMAKE_C_COMPILER=clang \
                -DCMAKE_CXX_STANDARD=20 \
                -DCMAKE_CXX_STANDARD_REQUIRED=ON \
                -DCMAKE_CXX_FLAGS="-fsanitize=memory -fsanitize-memory-track-origins -fno-omit-frame-pointer -O1 -g" \
                -DCMAKE_C_FLAGS="-fsanitize=memory -fsanitize-memory-track-origins -fno-omit-frame-pointer -O1 -g" \
                -DCMAKE_EXE_LINKER_FLAGS="-fsanitize=memory" \
                -DPERFORMANCE_BUILD=OFF \
                -DWARNING_MODE=ON \
                -DDEBUG_MODE=ON \
                -DBUILD_TESTS=ON \
                ..
          make -j$(nproc)
      
      - name: Run Memory Sanitizer Tests
        run: |
          export MSAN_OPTIONS="abort_on_error=0:print_stats=1:halt_on_error=0:exit_code=0:suppressions=test-workflows/msan_suppressions.txt"
          export MSAN_SYMBOLIZER_PATH=/usr/bin/llvm-symbolizer
          
          echo "Testing basic functionality with MSAN suppressions..."
          # Test basic functionality first - these should run without MSAN warnings
          build-msan/bin/vglog-filter --help
          build-msan/bin/vglog-filter -V
          
          echo "Running smoke test with MSAN suppressions..."
          # Run the smoke test
          ./test/smoke_test.sh build-msan/bin/vglog-filter