name: ShellCheck

permissions:
  contents: read

on:
  push:
    paths:
      - 'build.sh'
  pull_request:
    paths:
      - 'build.sh'

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install ShellCheck
        run: sudo apt-get update && sudo apt-get install -y shellcheck
      - name: Run ShellCheck
        run: shellcheck build.sh 
