name: Auto Version Bump with Semantic Release Notes

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'VERSION'
      - 'doc/VERSIONING.md'
      - '.github/workflows/version-bump.yml'

jobs:
  version-bump:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    env:
      NEW_VERSION: ""
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Setup Git
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
    
    - name: Check for version bump commits
      id: check-commits
      run: |
        # Get commits since last tag
        if git describe --tags --abbrev=0 2>/dev/null; then
          LAST_TAG=$(git describe --tags --abbrev=0)
          echo "Last tag: $LAST_TAG"
          COMMITS=$(git log --oneline $LAST_TAG..HEAD)
        else
          echo "No tags found, using all commits"
          COMMITS=$(git log --oneline)
        fi
        
        # Sanitize commit messages for GitHub Actions output
        # Create a simple summary instead of raw commit messages
        COMMIT_COUNT=$(echo "$COMMITS" | wc -l)
        SANITIZED_COMMITS="Total commits since last tag: $COMMIT_COUNT"
        
        echo "Commit count: $COMMIT_COUNT"
        echo "First few commits:"
        echo "$COMMITS" | head -5
        
        # Debug: Show what conventional commit types we found
        echo "Analyzing conventional commits..."
        if echo "$COMMITS" | grep -q "^[a-f0-9]* .*BREAKING CHANGE:"; then
          echo "  ✓ Found BREAKING CHANGE commits"
        fi
        if echo "$COMMITS" | grep -q "^[a-f0-9]* feat:"; then
          echo "  ✓ Found feat commits"
        fi
        if echo "$COMMITS" | grep -q "^[a-f0-9]* fix:"; then
          echo "  ✓ Found fix commits"
        fi
        if echo "$COMMITS" | grep -q "^[a-f0-9]* \(docs\|style\|refactor\|perf\|test\|chore\):"; then
          echo "  ✓ Found other conventional commits"
        fi
        
        # Check for conventional commit types
        # Look for breaking changes first (major version)
        if echo "$COMMITS" | grep -q "^[a-f0-9]* .*BREAKING CHANGE:"; then
          echo "Found breaking change commits"
          echo "bump_type=major" >> $GITHUB_OUTPUT
          echo "found_breaking=true" >> $GITHUB_OUTPUT
        # Look for feat commits (minor version)
        elif echo "$COMMITS" | grep -q "^[a-f0-9]* feat:"; then
          echo "Found feat commits"
          echo "bump_type=minor" >> $GITHUB_OUTPUT
          echo "found_feat=true" >> $GITHUB_OUTPUT
        # Look for fix commits (patch version)
        elif echo "$COMMITS" | grep -q "^[a-f0-9]* fix:"; then
          echo "Found fix commits"
          echo "bump_type=patch" >> $GITHUB_OUTPUT
          echo "found_fix=true" >> $GITHUB_OUTPUT
        # Look for other conventional commit types that might indicate changes
        elif echo "$COMMITS" | grep -q "^[a-f0-9]* \(feat\|fix\|docs\|style\|refactor\|perf\|test\|chore\):"; then
          echo "Found other conventional commits"
          echo "bump_type=patch" >> $GITHUB_OUTPUT
          echo "found_other=true" >> $GITHUB_OUTPUT
        else
          echo "No conventional commits found"
          echo "bump_type=none" >> $GITHUB_OUTPUT
        fi
        
        echo "commits_since_last_tag=$SANITIZED_COMMITS" >> $GITHUB_OUTPUT
    
    - name: Bump version if needed
      if: steps.check-commits.outputs.bump_type != 'none'
      run: |
        echo "Bumping version type: ${{ steps.check-commits.outputs.bump_type }}"
        
        # Make sure the script is executable
        chmod +x ./dev-bin/bump-version
        
        # Show current version
        echo "Current version: $(cat VERSION)"
        
        # Bump version (without creating tag, let the release action handle it)
        ./dev-bin/bump-version ${{ steps.check-commits.outputs.bump_type }} --commit
        
        # Show new version
        NEW_VERSION=$(cat VERSION)
        echo "New version: $NEW_VERSION"
        echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_ENV
        
        # Push changes
        echo "Pushing to main branch..."
        git push origin main
    
    - name: Create Release
      if: steps.check-commits.outputs.bump_type != 'none'
      uses: softprops/action-gh-release@v1
      with:
        tag_name: v${{ env.NEW_VERSION }}
        name: Release v${{ env.NEW_VERSION }}
        generate_release_notes: true
        body: |
          ## Version Bump Type
          - **${{ steps.check-commits.outputs.bump_type }}** version bump
          
          ## Automated Release
          This release was automatically generated by vglog-filter's version bump workflow.
          
          ---
          *Release notes below are automatically generated by GitHub based on conventional commits.*
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 